language: python
python:
- 3.8
- 3.7
- 3.6
- 3.5
- 2.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: andrewm4894
  password:
    secure: bbysqvoHAClBVhbwfIV2Ibkd813uwk2i/l8rlvjUH1Wobv+inf2pnXlE55qPWtFfywGZvYnlPcPEmHLvcnn1QPV8ELI8unVnoS6xQ76eoGPk89gn9DULnLhaMjQYgpuxl66LJ78YsVBntS02wJ3WWYHtcIMIiZw4+O1XOE83FADLYbJQ6p1GmxJ1czATKVdSOBfWrgH8H2u85eqhBz9aZ0slaE5y6JpngUXhwF2uS2aQ41PHG6Iu+Ywc0keC8nV8YkwRWWAYKl+dfyMa0CtYaun456zDDDlaHXNXzOBFSbxdwuFnPKcgc7WVlWGumAnLNdwdTyo+HsYQ0QAm9UMEhp61aDZCmlMybmDBHIOKmE82jxg/3hPyZyQ7eypCNkL8vOSl+MwzbLaoxL2np4iSTdx4IfkZUvVGdevX/oavAETqsmxYZ5Pl7EWOHPBwbr20bz7eJKDzP1qpiDZYsD92dXRmrIEAOTMuoQm1m+0xRdrkcdZ3yk9Riw864xXgEnsDzAgJs//1FNHINCpwukQhlDf/UoJp7gfFnit7QYwESEa/0DXSeCzevNEKELRfIW8v+ZrpWXvRNkVHDOqdyqDD6uoadA68lA8yO5imoTkNUG7eA/8toBQhsvUDYnl3PfI2EdpIrZaFCYTKr84EJSa1MasQbrkJCZKLJeTWhyD1CTQ=
  on:
    tags: true
    repo: andrewm4894/am4894dev2
    python: 3.8
